name: drivers
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  email_validator: ^3.0.0
  intl_phone_field: ^3.2.0
  firebase_auth: ^5.5.1
  firebase_database: ^11.3.4
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.4
  fluttertoast: ^8.2.12
  google_maps_flutter: ^2.12.0
  geolocator: ^13.0.3
  geocoder2: ^1.4.0
  flutter_geofire: ^2.0.6
  flutter_polyline_points: ^1.0.0
  location: ^8.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
   - images/
