// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaY0FnIWdlCQ1pbqfnaiNxnLB4wn0lX_E',
    appId: '1:862219094987:android:aef5e2a1ebbf562521c44e',
    messagingSenderId: '862219094987',
    projectId: 'ubride-2cbac',
    databaseURL: 'https://ubride-2cbac-default-rtdb.firebaseio.com',
    storageBucket: 'ubride-2cbac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9JEQZII8I3tE9co1oyxMzQ0ucGDgquqw',
    appId: '1:862219094987:ios:4cc4cc321e2f06f521c44e',
    messagingSenderId: '862219094987',
    projectId: 'ubride-2cbac',
    databaseURL: 'https://ubride-2cbac-default-rtdb.firebaseio.com',
    storageBucket: 'ubride-2cbac.firebasestorage.app',
    iosBundleId: 'com.example.drivers',
  );
}
